// Generated by CoffeeScript 1.4.0
var err, gen, is_arr, is_fun, is_num, is_obj, is_str, log, print;

is_arr = Array.isArray;

is_str = function(item) {
  return typeof item === 'string';
};

is_num = function(item) {
  return typeof item === 'number';
};

is_fun = function(item) {
  return typeof item === 'function';
};

is_obj = function(item) {
  return typeof item === 'object';
};

gen = function(item) {
  return JSON.stringify(item, null, 2);
};

log = console.log;

err = function(info) {
  throw new Error(info);
};

print = function(item) {
  log(item);
  return print;
};

exports.init = {
  print: print
};
