// Generated by CoffeeScript 1.4.0
var add, comment, do_func, err, fn, gen, get, get_env, is_arr, is_fun, is_num, is_obj, is_str, log, number, print, set, set_env, spawn, string;

is_arr = Array.isArray;

is_str = function(item) {
  return typeof item === 'string';
};

is_num = function(item) {
  return typeof item === 'number';
};

is_fun = function(item) {
  return typeof item === 'function';
};

is_obj = function(item) {
  return typeof item === 'object';
};

gen = function(item) {
  return JSON.stringify(item, null, 2);
};

log = console.log;

err = function(info) {
  throw new Error(info);
};

spawn = function(scope) {
  var child;
  child = {};
  child.__proto__ = scope;
  return child;
};

print = function(item, scope) {
  if (is_str(item)) {
    log(scope[item]);
  } else if (is_arr) {
    log(scope.read(item, scope));
  } else {
    log(item);
  }
  return print;
};

number = function(item) {
  return Number(item);
};

string = function(item, scope) {
  var ret;
  ret = is_arr(item) ? scope.read(item, scope) : is_str(item) ? scope[item] : String(item);
  if (is_fun(ret)) {
    return ret.toString(2);
  } else if (is_obj(ret)) {
    return JSON.stringify(ret, null, 2);
  } else {
    return String(ret);
  }
};

set = function(key, scope) {
  return function(value) {
    var ret;
    scope[key] = {};
    if (is_str(value)) {
      scope[key] = scope[value];
    } else if (is_arr(value)) {
      ret = scope.read(value, scope);
      scope[key] = ret;
    }
    return scope[key];
  };
};

get = function(item, scope) {
  if (is_str(item)) {
    return scope[item];
  } else if (is_arr(item)) {
    return scope.read(item, scope);
  } else {
    return err("can't get item: " + item);
  }
};

add = function(item, scope) {
  return item.map(function(key) {
    return get(key, scope);
  }).reduce(function(x, y) {
    return x + y;
  });
};

comment = function() {
  return comment;
};

get_env = function(item, scope) {
  return scope;
};

set_env = function(item, scope) {
  var key, value, _ref, _results;
  _ref = scope[item];
  _results = [];
  for (key in _ref) {
    value = _ref[key];
    _results.push(scope[key] = value);
  }
  return _results;
};

fn = function(item1, scope) {
  return function(item2) {
    var child, ret;
    child = spawn(scope);
    if (item1[0] != null) {
      return ret = function(arg) {
        var key;
        key = item1.shift();
        child[key] = is_str(arg) ? scope[arg] : is_arr(arg) ? scope.read(arg, scope) : err("wrong arg " + arg + " in fn");
        if (item1[0] != null) {
          return ret;
        } else {
          return get(item2, child);
        }
      };
    } else {
      return function() {
        return get(item2, child);
      };
    }
  };
};

do_func = function(item, scope) {
  scope.read(item, scope);
  return do_func;
};

exports.init = {
  is_arr: is_arr,
  is_str: is_str,
  is_str: is_str,
  is_obj: is_obj,
  is_fun: is_fun,
  is_num: is_num,
  print: print,
  number: number,
  string: string,
  "+": add,
  set: set,
  get: get,
  comment: comment,
  "set-env": set_env,
  "get-env": get_env,
  fn: fn,
  "do": do_func
};
